name: uk-regional-stats
channels:
  - defaults
dependencies:
  - attrs
  - backcall
  - blas
  - bleach
  - boost-cpp
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - click
  - click-plugins
  - cligj
  - curl
  - cycler
  - decorator
  - defusedxml
  - descartes
  - entrypoints
  - expat
  - fiona
  - fontconfig
  - freetype
  - freexl
  - gdal
  - geopandas
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - hdf4
  - hdf5
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - json-c
  - jsonschema
  - jupyter_client
  - jupyter_core
  - kealib
  - kiwisolver
  - krb5
  - libboost
  - libcurl
  - libdap4
  - libedit
  - libffi
  - libgdal
  - libiconv
  - libkml
  - libnetcdf
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libxml2
  - mapclassify
  - markupsafe
  - matplotlib
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - munch
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - palettable
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj4
  - prometheus_client
  - prompt_toolkit
  - psycopg2
  - ptyprocess
  - pygments
  - pyparsing
  - pyproj
  - pyrsistent
  - pysal
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - readline
  - rtree
  - scipy
  - seaborn
  - send2trash
  - setuptools
  - shapely
  - six
  - sqlalchemy
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - xerces-c
  - xlrd
  - xz
  - zeromq
  - zlib
  - zstd